services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - voltguard-network
    command: ["npm", "run", "dev"]

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - voltguard-network
  #   devices:
  #     - /dev/video0:/dev/video0  # Pass webcam to container
  #   privileged: true  # Required for camera access on some systems

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${PG_USER:-voltguard_user}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-securepassword}
      POSTGRES_DB: ${PG_DATABASE:-voltguard_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - voltguard-network

networks:
  voltguard-network:
    driver: bridge

volumes:
  pgdata: